// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Inputset2 struct {
	Data1 string  `json:"data1"`
	Data2 *string `json:"data2"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
